### PR TITLE
fix: swap isomorphic-fetch for node-fetch for security issue

### PR DESCRIPTION
**Pull request by shazron**
See #95

### CODE REVIEW

**Review by rabbah — APPROVED** [review]

**Review by alexkli — COMMENTED** [review]
I believe there is no fundamental reason to use any special cross-platform `fetch` implementation here, this can actually just use a standard `node-fetch` (or in future the new built-in node fetch module)... unless `fetch-retry` does not work with a latest [node-fetch](https://www.npmjs.com/package/node-fetch) (v2) for some reason. But this comment says v2 should work fine: https://github.com/jonbern/fetch-retry/issues/64#issuecomment-957794522

`isomorphic-fetch` came in in this commit https://github.com/apache/openwhisk-wskdebug/pull/12 when updating dependencies... previously `fetch-retry` came with `isomorphic-fetch` but in newer versions one had to explicitly depend on it.

IMO `node-fetch` is a better dependency to have, so I would suggest to try out `node-fetch` instead of moving to another library `cross-fetch` that at least I have no experience with.

**Comment by shazron** [comment]
@alexkli ok, I will update with node-fetch. I didn't delve into why `isomorphic-fetch` was used in this lib (perhaps there is an in-browser use case I reckoned) and `cross-fetch` seemed a drop-in replacement.

**Comment by shazron** [comment]
@alexkli PR updated

**Review by alexkli — APPROVED** [review]
Thanks @shazron. Code change LGTM. However, the CI build is failing in all nodejs versions ([here is node 14](https://app.travis-ci.com/github/apache/openwhisk-wskdebug/jobs/565054672)). I can't find the actual error at quick glance...

**Comment by shazron** [comment]
@alexkli all tests pass except this `ngrok` thing that I have no idea how to fix:
```
The command '/bin/sh -c wskdebug --ngrok myaction 2>&1 | grep -A 10 "ngrok dependency required for --ngrok is not installed"' returned a non-zero code: 1
```

**Comment by alexkli** [comment]
Hmm, it looks unrelated, but it worked in the last PR #92 that got merged.

This error happens in the posttest script which you can run using `npm run posttest`.

The test logic is in here: https://github.com/apache/openwhisk-wskdebug/tree/master/test/install

It spins up a container and tries to install wskdebug from scratch in there and see that it runs. As part of that it checks for the ngrok installation check we have in wskdebug: https://github.com/apache/openwhisk-wskdebug/blob/master/test/install/Dockerfile#L34-L35

You could run this locally and change that line to just `wskdebug --ngrok myaction` to see what the actual output is.

**Comment by shazron** [comment]
The error message I get when making that change and running `npm run posttest` is:
```
 => ERROR [ 8/10] RUN wskdebug --ngrok myaction                                             12.7s
------
 > [ 8/10] RUN wskdebug --ngrok myaction:
#13 12.66
#13 12.66 Error: Unknown Error From API: socket hang up
------
executor failed running [/bin/sh -c wskdebug --ngrok myaction]: exit code: 1
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

ERROR: Installation test failed!
```
As you can see the error message has changed from what is expected. I double checked I don't have ngrok installed globally before running it.

I'll check in the change so the CI can run.

**Comment by shazron** [comment]
I'll debug why it doesn't go to https://github.com/apache/openwhisk-wskdebug/blob/1ec715d98136811bea30eb6a82b378d78e356252/src/agentmgr.js#L94

**Comment by shazron** [comment]
@alexkli it's pretty clear now that there is a bug in the existing code, and nothing related to this PR. This line: https://github.com/apache/openwhisk-wskdebug/blob/1ec715d98136811bea30eb6a82b378d78e356252/src/agentmgr.js#L23 the result is always defined so this logic will always be false: https://github.com/apache/openwhisk-wskdebug/blob/1ec715d98136811bea30eb6a82b378d78e356252/src/agentmgr.js#L93 (if (true && !true) => if (false))

I'm not sure if https://github.com/apache/openwhisk-wskdebug/blob/1ec715d98136811bea30eb6a82b378d78e356252/src/agentmgr.js#L23 would ever throw an error though, just by inspection

**Comment by shazron** [comment]
Solved it! npm@7 is default in the latest node-lts, and by default will install peer dependencies. I added the flag `--legacy-peer-deps` to the `RUN npm install -g openwhisk-wskdebug.tgz` in the Dockerfile and now it works. Checking the change in.

**Comment by shazron** [comment]
@rabbah @alexkli all issues resolved. Perhaps this can be merged and a release started? Thanks!

**Comment by alexkli** [comment]
@shazron Thanks for digging deeper on this!

> npm 7 by default will install peer dependencies

That is a problem. ngrok must NOT be installed by default as it conflicts with the Apache licensing of openwhisk. That's why it was made a peer dependency - so that it does not get installed by default and that a developer must actively choose to install it themselves. While still working with the nodejs code and linters (that otherwise complain on missing require() dependencies).

Now if npm 7 has changed the peer behavior, we need to find a different way where a simple `npm install` would not install it. I think this is probably best to be fixed in a separate PR that we need to come up with and merge before this one (it essentially blocks any other changes to this repo).

Any smart ideas on how to achieve that? cc @rabbah 

Sorry that you run into this with your change.

**Comment by alexkli** [comment]
And also this was a reason: https://github.com/apache/openwhisk-wskdebug/issues/22

Not sure if that has improved as well.

**Comment by shazron** [comment]
Looks like it can be turned off in `.npmrc`:
```
legacy-peer-deps=true
```

However, that only works when you are doing `npm i` inside the repo root, and does not apply when installing it from a tarball like here: https://github.com/apache/openwhisk-wskdebug/blob/204f4e35b393a7d582106998c0967787102ec7ef/test/install/Dockerfile#L30

... at least according to my testing.

Not sure what the workaround is here, besides requiring before install:
```
npm config set legacy-peer-deps true --global
```

I prepared a PR where you can see that the ngrok test still fails: https://github.com/apache/openwhisk-wskdebug/pull/97

**Comment by alexkli** [comment]
@shazron There is a [peerDependenciesMeta](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta) with an `optional: true` flag that can be put in the package.json, which seems to be restoring the old behavior? Worth trying. If it works it should also be backwards compatible for users who still have npm < 7.

**Comment by shazron** [comment]
@alexkli https://github.com/apache/openwhisk-wskdebug/pull/97 now passes with your suggestion, once that is approved and merged, I rebase from master, and amend this PR to remove `--legacy-peer-deps` from the Dockerfile

**Review by rabbah — APPROVED** [review]

**Review by alexkli — APPROVED** [review]

**Pull request merged**
