### PR TITLE
fix: nodejs mounted action runner should set the right current working directory

### LINKED ISSUE #79: nodejs mounted action runner should set the right current working directory
In case actions are mounted locally in the container, the source directory is `/code` not `/nodejsAction`. The current working directory is normally `/nodejsAction` and some code might rely on it to find other files, so it should be adjusted accordingly if it's `/code`.

### PR DESCRIPTION
**Pull request by shazron**
Closes #79

Tested manually via action file in https://github.com/adobe/aio-cli-plugin-app/issues/282 and including a text file with the action (via the manifest.yml)

Debugged the action remotely and locally, and the current working directory listing includes the file that was included in the action.

`npm test` shows no errors.

### CODE REVIEW

**Review by alexkli — APPROVED** [review]
@shazron Not sure what happened, but I must have totally missed this PR! LGTM 👍

**Comment by alexkli** [comment]
@shazron before merging this, I would like to run the CI build with latest master, since the current state is out of date. Could you maybe merge latest master into your branch here?

@dgrove-oss I don't have access to the github settings for this project. Would it be possible to change the branch protection for `master` to enable "Require branches to be up to date before merging"? This way we'd enforce they are up to date and github shows us the "update" button on PRs (although I am not sure if that works for PRs from forks). Thanks!

**Comment by shazron** [comment]
@alexkli done! tests pass

**Comment by dgrove-oss** [comment]
We don't have direct access to the GitHub project settings, but we can control many of them through the .asf.yaml file.  if you submit a PR to change `strict` from false to true  (line: https://github.com/apache/openwhisk-wskdebug/blob/master/.asf.yaml#L36) that should do what you are asking.

**Pull request merged**
